ore_dict.clear('workbench')
ore_dict.add('workbench', item('extendedcrafting:crafting_table'))

ore_dict.add('amcAntimatter', item('amc_lts:antimatter_white'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_light_gray'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_orange'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_red'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_gray'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_pink'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_black'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_brown'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_blue'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_cyan'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_green'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_light_blue'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_lime'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_magenta'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_purple'))
ore_dict.add('amcAntimatter', item('amc_lts:antimatter_yellow'))

ore_dict.add('plateBlackIron', item('extendedcrafting:material', 2))
ore_dict.add('stickBlackIron', item('extendedcrafting:material', 3))
