mods.minecraft.crafting.shapedBuilder()
    .output(item('extendedcrafting:material', 8))
    .row('XY')
    .row('YX')
    .key('Y', ore('plateBlackIron'))
    .key('X', ore('plateIron'))
    .replace()
    .mirrored()
    .register()
