mods.minecraft.crafting.shapedBuilder()
    .output(item('extendedcrafting:crafting_table'))
    .row('XX')
    .row('XX')
    .key('X', ore('plankWood'))
    .register()

mods.minecraft.crafting.shapedBuilder()
    .output(item('extendedcrafting:table_basic'))
    .row('X')
    .row('Y')
    .key('Y', ore('workbench'))
    .key('X', item('extendedcrafting:material', 8))
    .replace()
    .register()
